### ISSUE TITLE
2 problems on excercise 4 of your leeraccess

### ISSUE THREAD

**Issue by Rogiervans** [bwelman/leeraccess#1]
I have reinstalled the snoep3651.accdb database after the here mentioned problem.
In taak 4.4 I select "Referentie integriteit afdwingen" and then I get the error: Microsoft Access kan geen relatie maken waarvoor referentiële integriteit moet worden afgedwongen.

**Comment by Rogiervans** [comment]
Sorry after all I have yet only1 problem. not 2.

**Comment by bwelman** [comment]
Ik kan het probleem niet reproduceren. Probeer het anders nog eens met een onbewerkte snoep365.accdb database.
Aan het einde van paragraaf 4.7.5 worden twee mogelijke oorzaken genoemd. Heb je deze onderzocht?

**Comment by Rogiervans** [comment]
Dank voor het snelle antwoord.
Nu ga ik onderzoeken waardoor het met de onbewerkte database wel lukt.

Groeten,
Rogier van Spaendonck

Op zo 26 nov 2023 om 13:01 schreef Ben Welman ***@***.***>:
